### ISSUE TITLE
Enabling multiple bllk-devices in a crail cluster

### ISSUE THREAD

**Issue by bissont** [zrlio/crail-blkdev#2]
Hi All, 

We'd like to add support for multiple block devices in a Crail cluster and like to get your feedback. For instance, two datanodes, each with an NVMe SSD served over NVMeF/iSCSI.

Currently, the Crail architecture doesn't support this with blk-dev. With SPDK-NVMeF and RDMA, the client establishes a direct connection to the datanode to issue an I/O (i.e., IP/port), so there is no mapping on the client side. However, with blk-dev, the namenode/datanode doesn't know about the mapping the client created to map the remote device(e.g., /dev/nvme0n1 on datanode is mapped to /dev/nvme3n1 on the client). As a result, only a single block device can be present in a crail cluster, which requires no mapping on the client-side.

In order to add support for this, we are thinking about adding an additional layer of indirection to keep track of the mapping between client and datanode block devices.

In order to do this, the design we are considering is to add an additional unique identifier (i.e., blkdev0) for the block device in a datanode:
crail.storage.blkdev.datapath: /dev/nvme0n1
crail.storage.blkdev.id: blkddev0

The client would also store a mapping of their virtual device to the unique identifier:
crail.storage.blkdev.datapath: /dev/nvme3n1
crail.storage.blkdev.id: blkddev0
...

The namenode would pull in the ids/sizes of datanode devices as they start and allocate blocks to the client based on these ids.

When a client wants to issue an I/O it would receive the id, such as blkdev0 from the namenode, and then map that id to its virtual device, /dev/nvme3n1, and use that to complete its I/O.

One of the challenges of this approach is that the client would need to explicitly keep track of all the block device mappings. Since this information already exists on the client (nvme connect creates that mapping), we are duplicating that state.

This is related to the following issue https://github.com/zrlio/crail/issues/26. However, the goal of this proposal is simpler, we'd like to support more than one device in a Crail cluster..

Any thoughts/opinions are appreciated!

Thanks,
Tim

**Comment by PepperJo** [comment]
Hi Tim,

> However, with blk-dev, the namenode/datanode doesn't know about the mapping the client created to map the remote device(e.g., /dev/nvme0n1 on datanode is mapped to /dev/nvme3n1 on the client).

This is correct however each client can have its own configuration file with the correct mapping to whatever block device is used. In theory we could store the registered datapath on the namenode
however we do not want to extend the RPC calls to support arbitrary length strings and we want to avoid string allocations on the namenode. These operations are costly and might limit your performance.

> As a result, only a single block device can be present in a crail cluster, which requires no mapping on the client-side.

I don't think that is restricted by the mapping. You could figure out which block device to use by the IP/key pair that you get on the client side. You can set IP/key to your liking when registering blocks.
Another possibility is to use mdadm and create a software RAID0 for your block devices.

> For instance, two datanodes, each with an NVMe SSD served over NVMeF/iSCSI.

We highly recommend using the NVMf storage tier since this will give you better performance compared to the block device solution which is mainly meant to support legacy storage systems.

Regards,
Jonas

**Comment by patrickstuedi** [comment]
Hi TIm,

Thanks for bringing this topic on the table. Here is my perspective. We should try to make the blk-dev work also for the case where multiple block devices are being exported. But I argue the general architecture of Crail is sufficient to make this possible with very little extra work. The general architecture of Crail is that a storage server (regardless of which type, so including RDMA, NVMe and Blk-dev) should export a single device, and exporting multiple devices should be done by starting multiple servers. I see that for the Blk-Dev tier that does not currently work, but it can be made work very easily. Here is a simple approach: add another config parameter that lists all the blk devices that are exported. Let's say you have 4 servers each exporting their block device. On the clients these block devices are mapped as /dev/blkdev1 .. /dev/blkdev4, Now all we have to do is to make the individual servers use either the IP, the port, or the key of their exported registration as an index into this array. The simplest might be to use the key. So storage server 1 that exports /dev/blkdev1 is registering this with key 0, while storage server 4 exporting /dev/blkdev4 is registering (with the namenode) this with key 3. At the client, when the client-side of the blk-dev tier is asked to read or write a block, the key is also provided so the client knows which block device to access.

Cheers,
  Patrick

**Comment by patrickstuedi** [comment]
We would definitely be very interested in a pull request that implements the above scheme.

**Comment by bissont** [comment]
Thanks the feedback guys. I really appreciate it.

> I don't think that is restricted by the mapping. You could figure out which block device to use by the IP/key pair that you get on the client side. You can set IP/key to your liking when registering blocks.

So that I'm on the same page as you guys, the above is the same as what Patrick described, but with more details (for someone new like me:-) )?

Awesome - I'll submit a prototype in a bit (week or so) and we can use that to continue the discussion.

**Comment by patrickstuedi** [comment]
Great, looking forward to it!

**Comment by bissont** [comment]
Hi,

I know it took a while to prototype, but any thoughts on the pull request?
https://github.com/zrlio/crail-blkdev/pull/3
